version: "3.9"

services:
  web-app:
    image: omnichem/omnichem_backend-app:1.0.0
    container_name: backend-app-OmniChem
    command: ./entrypoint.sh
    volumes:
      # - ./app:/home/app Это для локалки. Полезно для разработки
      - ./products:/home/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    container_name: db-postgres-OmniChem
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  
  omnibot-app:
    image: omnichem/omnichem-tg-bot:v1.0.1
    container_name: omnibot
    restart: always

volumes:
  postgres_data:
