version: "3.9"

services:
  web-app:
    image: omnichem/omnichem_backend-app:latest
    container_name: backend-app-OmniChem
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    container_name: db-postgres-OmniChem
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./dumps:/dumps
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  
  omnibot-app:
    image: omnichem/omnichem-tg-bot:v1.0.3
    container_name: omnibot
    restart: always
    env_file:
      - .env
    volumes:
      - ./omnibot_db:/app_tg_bot/omnibot_db

  frontend-app:
    image: omnichem/omnichem-frontend-app:v1.0.6
    container_name: omnichem-frontend-app
    ports:
      - "6688:6688"

  omnichemLand:
    image: omnichem/omnichem-landing:latest
    container_name: omnichemLand
    ports:
      - "4200:4200"
    restart: unless-stopped
    
volumes:
  postgres_data:
